version: '3'

services:
    barista:
      build: ./Barista/.
      ports:
        - "5003:80"
    coffeemachine:
      build: ./CoffeeMachine/.
      ports:
        - "5002:80"
    ui:
      build: ./UI/.
      ports:
        - "5001:80"