apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeemachine-ui-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffeemachine-ui
      zone: prod
      version: v1
  minReadySeconds: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: coffeemachine-ui
        zone: prod
        version: v1
    spec:
      containers:
        - name: coffeemachine-ui-pod
          image: coffeemachine_ui:v1
          ports: 
          - containerPort: 80
