apiVersion: v1
kind: Service
metadata:
  name: coffeemachine-barista-svc
  labels:
    app: coffeemachine-barista
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: coffeemachine-barista
    zone: prod
    version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeemachine-barista-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeemachine-barista
      zone: prod
      version: v1
  minReadySeconds: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: coffeemachine-barista
        zone: prod
        version: v1
    spec:
      containers:
        - name: coffeemachine-barista-pod
          image: 087812398137.dkr.ecr.us-east-1.amazonaws.com/coffeemachine/barista:1.0.0
          ports: 
          - containerPort: 80
          # resources:            
          #   limits:
          #     cpu: "1"
          #     memory: "250Mi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "100Mi"
              
