apiVersion: v1
kind: Service
metadata:
  name: coffeemachine-coffeemachine-svc
  labels:
    app: coffeemachine-coffeemachine
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
    protocol: TCP
  selector:
    app: coffeemachine-coffeemachine
    zone: prod
    version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeemachine-coffeemachine-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeemachine-coffeemachine
      zone: prod
      version: v1
  minReadySeconds: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: coffeemachine-coffeemachine
        zone: prod
        version: v1
    spec:
      containers:
        - name: coffeemachine-coffeemachine-pod
          image: coffeemachine_coffeemachine:v1
          imagePullPolicy: Always
          ports: 
          - containerPort: 80
          # resources:            
          #   limits:
          #     cpu: "1"
          #     memory: "250Mi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "100Mi"
              
