# Please read through https://learn.hashicorp.com/consul/kubernetes/minikube
# also https://www.consul.io/docs/platform/k8s/connect.html

# Choose an optional name for the datacenter
global:
  datacenter: dc1
  
  # Enable the Consul Web UI via a NodePort for Minikube setup
  ui:
    service:
      type: NodePort
  
  # Enable Connect for secure communication between nodes
  connectInject:
    enabled: true
  
  client:
    enabled: true
  
  # Use only one Consul server for local development
  server:
    replicas: 3
    bootstrapExpect: 1
    disruptionBudget:
      enabled: true
      maxUnavailable: 0