apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.barista }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Chart.Name }}{{ .Values.serviceNames.barista }}
  labels:
    {{- include "coffeemachine.labels" . | nindent 4 }}{{ .Values.serviceNames.barista }}
spec:
  replicas: {{ .Values.replicaCount.barista }}
  selector:
    matchLabels:
      {{- include "coffeemachine.selectorLabels" . | nindent 6 }}{{ .Values.serviceNames.barista }}
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-port": "service-port"
        "consul.hashicorp.com/service-tags": "barista"
        "consul.hashicorp.com/service-name": "{{ .Chart.Name }}{{ .Values.serviceNames.barista }}"
        "consul.hashicorp.com/connect-service-upstreams": "{{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}:{{ .Values.services.coffeemachine.port }}"
      labels:
        {{- include "coffeemachine.selectorLabels" . | nindent 8 }}{{ .Values.serviceNames.barista }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: container-{{ .Chart.Name }}{{ .Values.serviceNames.barista }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.barista.name }}:{{ .Values.images.barista.version }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
          - name: service-port
            containerPort: 8080
            protocol: TCP
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          livenessProbe:
            httpGet:
              path: "/health"
              port: service-port
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.barista }}
  labels:
    app: {{ .Values.serviceNames.barista }}
spec:
  type: {{ .Values.services.barista.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.services.barista.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}{{ .Values.serviceNames.barista }}
