apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}  
  labels:
    {{- include "coffeemachine.labels" . | nindent 4 }}{{ .Values.serviceNames.coffeemachine }}    
spec:
  replicas: {{ .Values.replicaCount.coffeemachine }}
  selector:
    matchLabels:
      {{- include "coffeemachine.selectorLabels" . | nindent 6 }}{{ .Values.serviceNames.coffeemachine }}
      app: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
  template:
    metadata:      
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-port": "http"
        "consul.hashicorp.com/service-name": {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
        "consul.hashicorp.com/service-tags": "coffeemachine"
      labels:
        {{- include "coffeemachine.selectorLabels" . | nindent 8 }}{{ .Values.serviceNames.coffeemachine }}
        app: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
    spec:
      hostname: {{ .Values.serviceNames.coffeemachine }}
      subdomain: {{ .Chart.Name }}
      serviceAccountName: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: container-{{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.coffeemachine.name }}:{{ .Values.images.coffeemachine.version }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
          - name: coffmach-http
            containerPort: 80
            protocol: TCP
          - name: coffmach-https
            containerPort: 443
            protocol: TCP
          livenessProbe:
            httpGet:
              path: "/health"
              port: coffmach-http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}  
  labels:
    app: {{ .Values.serviceNames.coffeemachine }}
spec:
  type: {{ .Values.services.coffeemachine.type }}
  ports:
    - port: 80
      targetPort: coffmach-http
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}{{ .Values.serviceNames.coffeemachine }}