apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.serviceNames.coffeemachine }}
  labels:
    {{- include "coffeemachine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.coffeemachine }}
  selector:
    matchLabels:
      {{- include "coffeemachine.selectorLabels" . | nindent 6 }}{{ .Values.serviceNames.coffeemachine }}
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-port": "http"
        "consul.hashicorp.com/service-tags": "coffeemachine"
      labels:
        {{- include "coffeemachine.selectorLabels" . | nindent 8 }}{{ .Values.serviceNames.coffeemachine }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.serviceNames.coffeemachine }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.coffeemachine.name }}:{{ .Values.images.coffeemachine.version }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffeemachine.fullname" . }}{{ .Values.serviceNames.coffeemachine }}
  labels:
    app: {{ .Values.serviceNames.coffeemachine }}
spec:
  type: {{ .Values.services.coffeemachine.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.services.coffeemachine.port }}
      protocol: TCP
  selector:
    app: {{ include "coffeemachine.fullname" . }}{{ .Values.serviceNames.coffeemachine }}