apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Chart.Name }}{{ .Values.serviceNames.ui }}
  labels:
    {{- include "coffeemachine.labels" . | nindent 4 }}{{ .Values.serviceNames.ui }}
spec:
  replicas: {{ .Values.replicaCount.ui }}
  selector:
    matchLabels:
      {{- include "coffeemachine.selectorLabels" . | nindent 6 }}{{ .Values.serviceNames.ui }}
      app: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-port": "http"
        "consul.hashicorp.com/service-tags": "ui"
        "consul.hashicorp.com/service-name": "{{ .Chart.Name }}{{ .Values.serviceNames.ui }}"
        "consul.hashicorp.com/connect-service-upstreams": "{{ .Chart.Name }}{{ .Values.serviceNames.barista }}:{{ .Values.services.barista.port }}:{{ .Values.datacenter }}"
      labels:
        {{- include "coffeemachine.selectorLabels" . | nindent 8 }}{{ .Values.serviceNames.ui }}
        app: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}
    spec:
      volumes: 
      - name: shared-data
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: container-{{ .Chart.Name }}{{ .Values.serviceNames.ui }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.ui.name }}:{{ .Values.images.ui.version }}"
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
        livenessProbe:
          tcpSocket:
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}
  labels:
    app: {{ .Values.serviceNames.ui }}
spec:
  type: {{ .Values.services.ui.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}{{ .Values.serviceNames.ui }}