apiVersion: v1
kind: Service
metadata:
  name: coffeemachine-ui-svc
  labels:
    app: coffeemachine-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: coffeemachine-ui
    zone: prod
    version: v1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeemachine-ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeemachine-ui
      zone: prod
      version: v1
  minReadySeconds: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: coffeemachine-ui
        zone: prod
        version: v1
    spec:
      containers:
        - name: coffeemachine-ui-pod
          image: coffeemachine_ui:1.0.0
          ports: 
          - containerPort: 80
              
